# Generated by Django 2.0.7 on 2020-10-04 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=30)),
                ('maps', models.CharField(max_length=10)),
                ('team', models.CharField(max_length=7)),
                ('perspective', models.CharField(max_length=4)),
                ('price', models.IntegerField()),
                ('ranks', models.IntegerField()),
                ('amount_kill', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
