# Generated by Django 3.1.1 on 2020-09-30 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_totalusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TotalUsers',
            new_name='TotalUser',
        ),
    ]
