# Generated by Django 3.1.1 on 2020-09-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200930_0817'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TotalUser',
        ),
    ]
