# Generated by Django 2.0.7 on 2020-10-03 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_totaluser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpassword',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserPassword',
        ),
    ]
